import { Schema, model, models } from "mongoose";

const TeamSchema = new Schema(
  {
    name: { type: String, required: true },
    logoUrl: { type: String, default: "" },
    captain: { type: Schema.Types.ObjectId, ref: "User", required: true },
    tournament: {
      type: Schema.Types.ObjectId,
      ref: "Tournament",
      required: true,
    },
    tournamentGame: {
      type: Schema.Types.ObjectId,
      ref: "TournamentGame",
      required: true,
    },
    club: { type: Schema.Types.ObjectId, ref: "Club" },
    status: {
      type: String,
      enum: ["active", "pending", "disqualified"],
      default: "pending",
    },
    locked: { type: Boolean, default: false },
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

export const Team = models.Team || model("Team", TeamSchema);
